# Generated by Django 3.1 on 2020-08-12 17:21

import basepage.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basepage.category')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.FilePathField(path=basepage.models.images_path)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='OptionParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basepage.option')),
            ],
        ),
        migrations.CreateModel(
            name='OptionProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('option_parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basepage.optionparameter')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
                ('main_image', models.FilePathField(path=basepage.models.images_path)),
                ('category', models.ManyToManyField(to='basepage.Category')),
                ('images', models.ManyToManyField(to='basepage.Image')),
                ('options', models.ManyToManyField(through='basepage.OptionProduct', to='basepage.OptionParameter')),
            ],
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basepage.product'),
        ),
    ]
