# Generated by Django 3.1.2 on 2020-12-24 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('basepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product', verbose_name='Товар'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wish',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='product.product'),
            preserve_default=False,
        ),
    ]
