# Generated by Django 3.1.2 on 2020-11-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionparameter',
            name='option',
        ),
        migrations.RemoveField(
            model_name='optionproduct',
            name='option_parameter',
        ),
        migrations.RemoveField(
            model_name='optionproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='OptionParameter',
        ),
        migrations.DeleteModel(
            name='OptionProduct',
        ),
    ]
