# Generated by Django 3.1.2 on 2021-03-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0002_auto_20210310_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymouscustomer',
            name='token',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
