# Generated by Django 3.1.2 on 2020-12-24 12:14

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0002_auto_20201224_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='basepage.review', verbose_name='Родитель'),
        ),
    ]
