# Generated by Django 3.1.2 on 2020-11-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0003_auto_20201109_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, related_name='Характеристики', to='basepage.Product'),
        ),
    ]
