# Generated by Django 3.1.2 on 2020-11-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0003_auto_20201120_0722'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSortType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
    ]
