# Generated by Django 3.1.2 on 2020-10-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0003_wish'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='item',
            new_name='product',
        ),
    ]
