# Generated by Django 3.1.2 on 2020-12-24 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0003_auto_20201224_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='level',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='rght',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
    ]
