# Generated by Django 3.1.2 on 2020-11-20 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0004_auto_20201120_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductSortType',
        ),
    ]
