# Generated by Django 3.1.2 on 2020-11-09 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0004_auto_20201109_1640'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionproduct',
            name='options',
        ),
        migrations.AddField(
            model_name='optionproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Характеристики', to='basepage.product'),
        ),
    ]
