# Generated by Django 3.1.2 on 2020-11-09 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0005_auto_20201109_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionproduct',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Характеристики', to='basepage.product'),
            preserve_default=False,
        ),
    ]
