# Generated by Django 3.1.2 on 2020-11-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0005_auto_20201106_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customergender',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Пол'),
        ),
    ]
