# Generated by Django 3.1.2 on 2021-01-12 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0005_compare'),
    ]

    operations = [
        migrations.AddField(
            model_name='compare',
            name='anonymous_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basepage.anonymouscustomer'),
        ),
    ]
