# Generated by Django 3.1.2 on 2020-10-20 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0006_auto_20201020_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='basepage.product'),
        ),
    ]
