# Generated by Django 3.1.2 on 2020-11-09 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0006_auto_20201109_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionproduct',
            name='parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basepage.option'),
        ),
        migrations.AlterField(
            model_name='optionproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Характеристики', to='basepage.product'),
        ),
    ]
