# Generated by Django 3.1.2 on 2020-12-02 12:08

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0006_auto_20201130_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='main_image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='Categories/', verbose_name='Изображение'),
        ),
    ]
