# Generated by Django 3.1.2 on 2020-10-13 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0006_auto_20201013_1340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='game_screen',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='basepage.product', verbose_name='Игра'),
        ),
    ]
