# Generated by Django 3.1.2 on 2020-12-02 12:25

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0007_auto_20201202_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='images/default/product/404.png', upload_to='Products/', verbose_name='Изображение'),
        ),
    ]
