# Generated by Django 3.1.2 on 2021-01-13 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0007_auto_20210112_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='anonymous_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basepage.anonymouscustomer'),
        ),
        migrations.AlterField(
            model_name='wish',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wish', to=settings.AUTH_USER_MODEL),
        ),
    ]
