# Generated by Django 3.1.2 on 2020-11-16 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0007_auto_20201109_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='advantages',
            field=models.TextField(blank=True, max_length=2500, verbose_name='Достоинства'),
        ),
        migrations.AddField(
            model_name='rating',
            name='disadvantages',
            field=models.TextField(blank=True, max_length=2500, verbose_name='Недостатки'),
        ),
        migrations.AddField(
            model_name='rating',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='basepage.rating', verbose_name='Родитель'),
        ),
        migrations.AddField(
            model_name='rating',
            name='text',
            field=models.TextField(blank=True, max_length=5000, verbose_name='Коментарий'),
        ),
        migrations.AlterField(
            model_name='optionproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='basepage.product'),
        ),
    ]
