# Generated by Django 3.1.2 on 2020-11-06 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0007_auto_20201106_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
