# Generated by Django 3.1.2 on 2020-11-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0008_auto_20201116_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Сообщение'),
        ),
    ]
