# Generated by Django 3.1.2 on 2021-01-28 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0008_auto_20210113_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
