# Generated by Django 3.1.2 on 2020-12-02 13:41

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0008_auto_20201202_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='images/default/product/404.png', upload_to='Categories/', verbose_name='Изображение'),
        ),
    ]
