# Generated by Django 3.1.2 on 2021-01-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0009_customer_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile',
        ),
    ]
