# Generated by Django 3.1.2 on 2020-10-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0009_auto_20201013_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ManyToManyField(related_name='images', to='basepage.Product', verbose_name='Игра'),
        ),
    ]
