# Generated by Django 3.1.2 on 2020-12-02 14:04

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0009_auto_20201202_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='Categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='Products/', verbose_name='Изображение'),
        ),
    ]
