# Generated by Django 3.1.2 on 2020-11-16 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0009_auto_20201116_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='advantages',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Достоинства'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='disadvantages',
            field=models.TextField(blank=True, max_length=2500, null=True, verbose_name='Недостатки'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='text',
            field=models.TextField(blank=True, max_length=5000, null=True, verbose_name='Коментарий'),
        ),
    ]
