# Generated by Django 3.1.2 on 2020-11-06 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0009_auto_20201106_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymouscustomer',
            name='cart',
        ),
        migrations.AddField(
            model_name='cart',
            name='anonymous_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basepage.anonymouscustomer'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
