# Generated by Django 3.1.2 on 2020-12-02 19:45

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0010_auto_20201202_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(unique=True, upload_to='ProductImages/'),
        ),
    ]
