# Generated by Django 3.1.2 on 2020-11-06 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0010_auto_20201106_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='anonymous_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basepage.anonymouscustomer'),
        ),
    ]
