# Generated by Django 3.1.2 on 2020-12-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0011_auto_20201202_2145'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='customergender',
            options={'verbose_name': 'Пол пользователя', 'verbose_name_plural': 'Пола пользователя'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Опция', 'verbose_name_plural': 'Опции'},
        ),
        migrations.AlterModelOptions(
            name='optionproduct',
            options={'verbose_name': 'Опции товара', 'verbose_name_plural': 'Опции товаров'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фото товара', 'verbose_name_plural': 'Фото товаров'},
        ),
        migrations.AlterModelOptions(
            name='wish',
            options={'verbose_name': 'Список желаемого', 'verbose_name_plural': 'Списки желаемого'},
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('0', 'Нет в наличии'), ('1', 'В наличии'), ('2', 'Ожидается'), ('3', 'Предзаказ')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
