# Generated by Django 3.1.2 on 2020-11-17 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0011_rating_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
