# Generated by Django 3.1.2 on 2020-11-17 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0012_auto_20201117_0926'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
