# Generated by Django 3.1.2 on 2020-12-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0012_auto_20201208_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='row',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
