# Generated by Django 3.1.2 on 2020-10-15 08:04

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0013_auto_20201015_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_avg',
            field=models.FloatField(default=1, verbose_name=django.db.models.aggregates.Avg('ratings__star', related_name='rating_avg')),
            preserve_default=False,
        ),
    ]
