# Generated by Django 3.1.2 on 2020-11-17 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0015_auto_20201117_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='star',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basepage.ratingstar', verbose_name='Звезда'),
        ),
    ]
