# Generated by Django 3.1.2 on 2020-10-15 09:42

from django.db import migrations, models
import django.db.models.aggregates


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0015_remove_product_rating_avg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_avg',
            field=models.FloatField(default=1, verbose_name=django.db.models.aggregates.Avg('ratings__star')),
            preserve_default=False,
        ),
    ]
