# Generated by Django 3.1.2 on 2020-10-15 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0016_product_rating_avg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_avg',
        ),
    ]
