# Generated by Django 3.1.2 on 2020-10-16 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0017_remove_product_rating_avg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default='images/default/product/404.png', upload_to='Products/', verbose_name='Изображение'),
        ),
    ]
