# Generated by Django 3.1.2 on 2020-11-18 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0019_auto_20201118_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basepage.category'),
        ),
    ]
