# Generated by Django 3.1.2 on 2020-11-18 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0021_auto_20201118_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionproduct',
            name='category',
        ),
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basepage.category'),
        ),
    ]
