# Generated by Django 3.1.2 on 2020-11-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0024_auto_20201119_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(blank=True, max_length=25555, null=True),
        ),
    ]
