# Generated by Django 3.1.2 on 2020-11-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0027_auto_20201119_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
