# Generated by Django 3.1.2 on 2020-11-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0028_auto_20201119_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='name',
            field=models.CharField(default=-1, max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='optionproduct',
            name='name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
