# Generated by Django 3.1.2 on 2020-11-19 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0031_auto_20201119_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='row',
            field=models.SmallIntegerField(blank=True, max_length=15, null=True),
        ),
    ]
