# Generated by Django 3.1.2 on 2021-01-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20201224_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='request_name',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
