# Generated by Django 3.1.2 on 2021-01-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0004_auto_20201224_1418'),
        ('product', '0003_option_request_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='category',
        ),
        migrations.AddField(
            model_name='option',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, to='basepage.Category'),
        ),
    ]
