# Generated by Django 3.1.2 on 2021-01-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0004_auto_20201224_1418'),
        ('product', '0004_auto_20210108_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='category',
            field=models.ManyToManyField(to='basepage.Category'),
        ),
    ]
