# Generated by Django 3.1.2 on 2021-02-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210109_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionproduct',
            name='name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
