# Generated by Django 3.1.2 on 2021-02-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210213_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionproduct',
            name='name',
            field=models.CharField(blank=True, default=1, max_length=225),
            preserve_default=False,
        ),
    ]
