# Generated by Django 3.1.2 on 2021-02-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210217_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionproduct',
            name='name',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
