# Generated by Django 3.1 on 2020-08-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0004_auto_20200813_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, to='basepage.Image'),
        ),
    ]
