# Generated by Django 3.1 on 2020-08-24 16:08

import basepage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0008_auto_20200822_1539'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'permissions': [('authorized', 'Authorized user')]},
        ),
        migrations.AddField(
            model_name='category',
            name='main_image',
            field=models.FilePathField(blank=True, path=basepage.models.images_path),
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
