# Generated by Django 3.1.2 on 2020-10-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0009_auto_20200824_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='Categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(upload_to='Image/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='Products/', verbose_name='Изображение'),
        ),
    ]
