# Generated by Django 3.1.2 on 2020-10-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0011_auto_20201009_1616'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
