# Generated by Django 3.1.2 on 2020-12-28 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0004_auto_20201224_1418'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='parameter',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.RemoveField(
            model_name='filter',
            name='category',
        ),
        migrations.AddField(
            model_name='filter',
            name='category',
            field=models.ManyToManyField(to='basepage.Category'),
        ),
    ]
