# Generated by Django 3.1.2 on 2021-01-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20201228_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='model',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='filter',
            name='query',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
