# Generated by Django 3.1.2 on 2021-01-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20210107_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='request_name',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
