# Generated by Django 3.1.2 on 2021-01-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_filter_request_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='output',
            field=models.CharField(blank=True, choices=[('values', 'values'), ('values_list', 'values_list')], max_length=32, null=True),
        ),
    ]
