# Generated by Django 3.1.2 on 2021-01-07 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_filter_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
