# Generated by Django 3.1.2 on 2021-01-07 10:24

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_auto_20210107_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('0', 'default'), ('1', 'Type 1'), ('2', 'Type 2'), ('3', 'Type 3')], max_length=7, null=True),
        ),
    ]
