# Generated by Django 3.1.2 on 2021-01-07 10:25

import basepage.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0008_auto_20210107_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='category',
        ),
        migrations.AddField(
            model_name='filter',
            name='category',
            field=multiselectfield.db.fields.MultiSelectField(max_length=200, null=True, verbose_name=basepage.models.Category),
        ),
        migrations.AlterField(
            model_name='filter',
            name='type',
            field=models.CharField(blank=True, choices=[('0', 'default'), ('1', 'Type 1'), ('2', 'Type 2'), ('3', 'Type 3')], max_length=32, null=True),
        ),
    ]
