# Generated by Django 3.1.2 on 2021-01-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basepage', '0004_auto_20201224_1418'),
        ('category', '0009_auto_20210107_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='category',
        ),
        migrations.AddField(
            model_name='filter',
            name='category',
            field=models.ManyToManyField(to='basepage.Category'),
        ),
    ]
