# Generated by Django 3.1.2 on 2021-01-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0010_auto_20210107_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='output',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='sub_filter',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='sub_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filter',
            name='sub_output',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
