# Generated by Django 3.1.2 on 2021-01-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0011_auto_20210108_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='query',
        ),
        migrations.AddField(
            model_name='filter',
            name='state',
            field=models.CharField(choices=[('0', 'off'), ('1', 'on')], max_length=255, null=True),
        ),
    ]
