# Generated by Django 3.1.2 on 2021-01-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0012_auto_20210108_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='state',
            field=models.BooleanField(default=False, verbose_name='Состояние'),
        ),
    ]
