# Generated by Django 3.1.2 on 2021-01-11 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210109_1214'),
        ('category', '0013_auto_20210109_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='filter',
            name='model_parameter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.option'),
        ),
    ]
