# Generated by Django 3.1.2 on 2020-11-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('telegram', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('True', 'True'), ('False', 'False')], max_length=10)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройка магазина',
                'verbose_name_plural': 'Настройки магазина',
            },
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Пункт футера', 'verbose_name_plural': 'Пункты футера'},
        ),
        migrations.AlterField(
            model_name='footer',
            name='description',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
        migrations.DeleteModel(
            name='Settings',
        ),
        migrations.AddField(
            model_name='setting',
            name='footer',
            field=models.ManyToManyField(to='shop_settings.Footer'),
        ),
    ]
