# Generated by Django 3.1.2 on 2020-11-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0002_auto_20201119_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='footer',
        ),
        migrations.AddField(
            model_name='setting',
            name='footer',
            field=models.ManyToManyField(to='shop_settings.Footer'),
        ),
    ]
