# Generated by Django 3.1.2 on 2020-11-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0003_productsorttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsorttype',
            name='field',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
