# Generated by Django 3.1.2 on 2020-11-19 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0003_auto_20201119_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Пункт футера', 'verbose_name_plural': 'Пункты футера'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Настройка магазина', 'verbose_name_plural': 'Настройки магазина'},
        ),
        migrations.AlterField(
            model_name='footer',
            name='description',
            field=models.CharField(blank=True, max_length=20000, null=True),
        ),
    ]
