# Generated by Django 3.1.2 on 2020-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0004_productsorttype_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsorttype',
            name='order',
            field=models.PositiveIntegerField(blank=True, max_length=50, null=True),
        ),
    ]
