# Generated by Django 3.1.2 on 2020-11-30 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0005_auto_20201120_1501'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsorttype',
            options={'verbose_name': 'Сортировка товаров', 'verbose_name_plural': 'Сортировки товаров'},
        ),
    ]
