# Generated by Django 3.1.2 on 2020-12-04 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0007_auto_20201202_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slide',
            old_name='slide',
            new_name='image',
        ),
        migrations.AddField(
            model_name='setting',
            name='meta_description',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AddField(
            model_name='slider',
            name='place',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='slider',
            name='slides',
        ),
        migrations.AddField(
            model_name='slider',
            name='slides',
            field=models.ManyToManyField(to='shop_settings.Slide'),
        ),
    ]
