# Generated by Django 3.1.2 on 2020-12-08 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0008_auto_20201204_1037'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slide',
            options={'verbose_name': 'Слайд', 'verbose_name_plural': 'Слайды'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Слайдер', 'verbose_name_plural': 'Слайдеры'},
        ),
    ]
