# Generated by Django 3.1.2 on 2020-12-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_settings', '0009_auto_20201208_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsorttype',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slider',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='slider',
            name='width',
            field=models.PositiveIntegerField(),
        ),
    ]
