# Generated by Django 3.1.2 on 2021-04-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Город')),
                ('description_ru', models.CharField(max_length=255, null=True, verbose_name='Город')),
                ('description_uk', models.CharField(max_length=255, null=True, verbose_name='Город')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Город')),
                ('ref', models.CharField(max_length=255, verbose_name='Идентификатор города')),
                ('area', models.CharField(max_length=255, verbose_name='Область')),
                ('city_id', models.CharField(max_length=255, verbose_name='Код населенного пункта')),
                ('city_ref', models.CharField(max_length=255, verbose_name='Идентификатор (REF) типа населенного пункта')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=255, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('sender_ref', models.CharField(max_length=255, verbose_name='Sender Ref')),
                ('city', models.CharField(max_length=255, verbose_name='Город отправления')),
                ('contact_ref', models.CharField(max_length=255, verbose_name='Contact Ref')),
                ('status', models.BooleanField(default=False)),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('counterparty_type', models.CharField(blank=True, choices=[('Organization', 'Организация'), ('PrivatePerson', 'Частное лицо')], max_length=255, null=True, verbose_name='Плательщик')),
                ('counterparty_property', models.CharField(default='Recipient', max_length=255, null=True)),
                ('ref', models.CharField(blank=True, max_length=255, verbose_name='Идентификатор')),
            ],
            options={
                'verbose_name': 'Контрагент',
                'verbose_name_plural': 'Контрагент',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=255)),
                ('cost_on_site', models.CharField(max_length=255)),
                ('estimated_delivery_date', models.CharField(max_length=255)),
                ('int_doc_number', models.CharField(max_length=255)),
                ('type_document', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Отправление',
                'verbose_name_plural': 'Отправления',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payer_type', models.CharField(blank=True, choices=[('Recipient', 'Получатель'), ('Sender', 'Отправитель'), ('ThirdPerson', 'Третья особа')], max_length=255, null=True, verbose_name='Плательщик')),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Наличный расчет'), ('NonCash', 'Безналичный расчет')], max_length=255, null=True, verbose_name='Способ оплаты')),
                ('cargo_type', models.CharField(blank=True, choices=[('Parcel', 'Посилка'), ('Cargo', 'Вантаж'), ('Documents', 'Документи'), ('TiresWheels', 'Шини-диски'), ('Pallet', 'Палети')], max_length=255, null=True, verbose_name='Тип посылки')),
                ('volume_general', models.CharField(blank=True, max_length=255, null=True, verbose_name='Объем')),
                ('weight', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вес')),
                ('service_type', models.CharField(blank=True, choices=[('WarehouseWarehouse', 'Склад-Склад'), ('DoorsDoors', 'Двері-Двері'), ('DoorsWarehouse', 'Двері-Склад'), ('WarehouseDoors', 'Склад-Двері')], max_length=255, null=True, verbose_name='Вид доставки')),
                ('seats_amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Количество мест')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('cost', models.CharField(blank=True, max_length=5000, null=True, verbose_name='Цена')),
                ('city_sender', models.CharField(blank=True, max_length=255, null=True, verbose_name='Индитификатор города отправителя')),
                ('sender', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор отправителя')),
                ('sender_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор адреса отправителя')),
                ('contact_sender', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор контактного лица отправителя')),
                ('sender_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон отправителя')),
                ('recipient_city_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор города получателя')),
                ('recipient_area', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор области')),
                ('recipient_area_region', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор района')),
                ('recipient_address_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор номера отделения')),
                ('recipient_house', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор номера улицы')),
                ('recipient_flat', models.CharField(blank=True, max_length=255, null=True, verbose_name='Идентификатор этажа ')),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='ФИО получателя')),
                ('recipient_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Тип получателя')),
                ('recipients_phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон получателя')),
                ('date_time', models.DateField(null=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Накладная',
                'verbose_name_plural': 'Накладные',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Отделение')),
                ('description_ru', models.CharField(max_length=255, null=True, verbose_name='Отделение')),
                ('description_uk', models.CharField(max_length=255, null=True, verbose_name='Отделение')),
                ('description_en', models.CharField(max_length=255, null=True, verbose_name='Отделение')),
                ('ref', models.CharField(max_length=255, verbose_name='Идентификатор отделения')),
                ('number', models.CharField(max_length=255, verbose_name='Номер')),
                ('type_warehouse', models.CharField(max_length=255, verbose_name='Тип отделения')),
                ('city_description', models.CharField(max_length=255, verbose_name='Название населенного пункта')),
                ('city_description_ru', models.CharField(max_length=255, null=True, verbose_name='Название населенного пункта')),
                ('city_description_uk', models.CharField(max_length=255, null=True, verbose_name='Название населенного пункта')),
                ('city_description_en', models.CharField(max_length=255, null=True, verbose_name='Название населенного пункта')),
                ('city_ref', models.CharField(max_length=255, verbose_name='Идентификатор населенного пункта')),
            ],
            options={
                'verbose_name': 'Отделение',
                'verbose_name_plural': 'Отделения',
            },
        ),
    ]
