# Generated by Django 3.1.2 on 2020-12-13 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.CharField(choices=[('0', 'Не оплачено'), ('1', 'Ожидается оплата'), ('2', 'Оплачено')], default=0, max_length=255),
        ),
    ]
